-- Add missing columns to clientes table
ALTER TABLE clientes 
ADD COLUMN IF NOT EXISTS endereco TEXT,
ADD COLUMN IF NOT EXISTS cidade TEXT,
ADD COLUMN IF NOT EXISTS estado TEXT,
ADD COLUMN IF NOT EXISTS cep TEXT,
ADD COLUMN IF NOT EXISTS origem_lead TEXT,
ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'Ativo',
ADD COLUMN IF NOT EXISTS observacoes TEXT;