// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://twfemjhazetnubmepysn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR3ZmVtamhhemV0bnVibWVweXNuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc0NDA5MTQsImV4cCI6MjA3MzAxNjkxNH0.YahkWy_6kzyBNL0S-m3vbLJJ97SVQqZ_BfllVICB7zo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});